@startuml
namespace po {
    interface Compiler  {
        + SetFile( *File) 
        + ToWriter( io.Writer) error
        + ToBytes() []byte

    }
    class Entries << (S,Aquamarine) >> {
        + Equal(e2 Entries) bool
        + ContainsFunc(f <font color=blue>func</font>(Entry) bool) bool
        + ContainsUnifiedID(uid string) bool
        + CutHeader() Entries
        + BestIDRatio(e1 Entry) (int, int)
        + BestStrRatio(e1 Entry) (int, int)
        + IndexFunc(f <font color=blue>func</font>(Entry) bool) int
        + IndexByUnifiedID(uid string) int
        + Index(id string, context string) int
        + IsSorted() bool
        + IsSortedFunc(cmp ) bool
        + Sort() Entries
        + PrepareSorter(cmp ) <font color=blue>func</font>() Entries
        + SortFunc(cmp ) Entries
        + HasDuplicates() bool
        + CleanObsoletes() Entries
        + CleanDuplicates() Entries
        + CleanEmpties() Entries
        + SolveFunc(merger MergeFunc) Entries
        + Solve() Entries
        + CleanFuzzy() Entries
        + FuzzyFind(id string, context string) int
        + Validate() error
        + Header() Header

    }
    interface EntriesOrFile  {
    }
    class Entry << (S,Aquamarine) >> {
        + Flags []string
        + Comments []string
        + ExtractedComments []string
        + Previous []string
        + Obsolete bool
        + ID string
        + Context string
        + Plural string
        + Plurals PluralEntries
        + Str string
        + Locations Locations

        - markAsObsolete() 
        - markAsFuzzy() 

        + IsHeader() bool
        + Validate() error
        + UnifiedStr() string
        + UnifiedID() string
        + FullHash() uint32
        + Hash() uint32
        + Equal(x Entry) bool
        + IsPlural() bool
        + HasContext() bool
        + IsFuzzy() bool
        + String() string

    }
    class File << (S,Aquamarine) >> {
        + Name string

        + Equal(f2 File) bool
        + Set(id string, context string, e Entry) 
        + LoadByUnifiedID(uid string) string
        + Load(id string, context string) string

    }
    class Header << (S,Aquamarine) >> {
        + Template bool
        + Fields []HeaderField

        - sSet(key string, value string) 

        + String() string
        + ToConfig() HeaderConfig
        + Nplurals() uint
        + ToEntry() Entry
        + Register(key string, d ...string) 
        + Load(key string) string
        + Set(key string, value string) 

    }
    class HeaderConfig << (S,Aquamarine) >> {
        + Template bool
        + ProjectIDVersion string
        + ReportMsgidBugsTo string
        + POTCreationDate string
        + PORevisionDate string
        + LastTranslator string
        + LanguageTeam string
        + Language string
        + MimeVersion string
        + ContentType string
        + Charset string
        + ContentTransferEncoding string
        + Nplurals uint
        + Plural string
        + XGenerator string

        + Validate() []error
        + ToHeader() Header

    }
    class HeaderField << (S,Aquamarine) >> {
        + Key string
        + Value string

    }
    class Location << (S,Aquamarine) >> {
        + Line int
        + File string

        + Equal(l2 Location) bool

    }
    class Locations << (S,Aquamarine) >> {
        + Equal(l2 Locations) bool
        + IsSorted() bool
        + IsSortedFunc(cmp ) bool
        + Sort() Locations
        + SortFunc(cmp ) Locations

    }
    class MergeConfig << (S,Aquamarine) >> {
        + FuzzyMatch bool
        + KeepPreviousIDs bool
        + Sort bool
        + SortMode SortMode

        + ApplyOption(opts ...MergeOption) 

    }
    interface Parser  {
        + Parse() *File
        + Error() error
        + Errors() []error

    }
    class PluralEntries << (S,Aquamarine) >> {
        + Equal(p2 PluralEntries) bool
        + Solve() PluralEntries
        + IsSorted() bool
        + IsSortedFunc(cmp ) bool
        + Sort() PluralEntries
        + SortFunc(cmp ) PluralEntries

    }
    class PluralEntry << (S,Aquamarine) >> {
        + ID int
        + Str string

        + Equal(p2 PluralEntry) bool

    }
    class SortMode << (S,Aquamarine) >> {
        + SortMethod(entries Entries) <font color=blue>func</font>() Entries

    }
    class po.Cmp << (T, #FF7700) >>  {
    }
    class po.Entries << (T, #FF7700) >>  {
    }
    class po.HeaderOption << (T, #FF7700) >>  {
    }
    class po.Locations << (T, #FF7700) >>  {
    }
    class po.MergeFunc << (T, #FF7700) >>  {
    }
    class po.MergeOption << (T, #FF7700) >>  {
    }
    class po.PluralEntries << (T, #FF7700) >>  {
    }
    class po.SortMode << (T, #FF7700) >>  {
    }
}
"po.Entries" *-- "po.File"


"__builtin__.int" #.. "po.SortMode"
"po.<font color=blue>func</font>(*HeaderConfig) " #.. "po.HeaderOption"
"po.<font color=blue>func</font>(*MergeConfig) " #.. "po.MergeOption"
"po.<font color=blue>func</font>(Entry, Entry) *Entry" #.. "po.MergeFunc"
"po.<font color=blue>func</font>(X, X) int" #.. "po.Cmp"
"po.[]Entry" #.. "po.Entries"
"po.[]Location" #.. "po.Locations"
"po.[]PluralEntry" #.. "po.PluralEntries"
@enduml
