// Package generator provides the functionality to generate PO
// (Portable Object) files from an Abstract Syntax Tree (AST) representation.
// This package takes an AST generated by the `ast` package
// and converts it into a `types.File` data structure, which represents a complete PO file.
//
// Key Features:
// - Conversion of AST nodes into PO entries.
// - Handling of comments, flags, contexts, messages, and plural forms.
// - Generation of standard PO headers.
//
// Example Usage:
//
//	file := ast.NewFile("test.po", nodes...)
//	g := generator.New(file)
//	poFile := g.Generate()
//	if len(g.Errors()) > 0 {
//	    // Handle errors
//	}
//	fmt.Println(poFile)
//
// For more details, refer to the individual function and type documentation.
package generator
