@startuml
namespace parse {
    class MoConfig << (S,Aquamarine) >> {
        - lastCfg any

        + Endianness Endianness

        + RestoreLastCfg() 
        + ApplyOptions(opts ...MoOption) 

    }
    class MoParser << (S,Aquamarine) >> {
        - data []byte
        - filename string
        - errors []error

        + Config MoConfig

        - genBasics() (*bytes.Reader, binary.ByteOrder, error)
        - makeEntries(r *bytes.Reader, header *moHeader, msgIDStart []u32, msgIDLen []u32, msgStrStart []i32, msgStrLen []i32) po.Entries

        + Error() error
        + Errors() []error
        + ParseWithOptions(opts ...MoOption) *po.File
        + Parse() *po.File

    }
    class PoConfig << (S,Aquamarine) >> {
        - lastCfg any
        - markAllAsObsolete bool

        + IgnoreComments bool
        + IgnoreAllComments bool
        + Logger *log.Logger
        + SkipHeader bool
        + CleanDuplicates bool
        + ParseObsoletes bool
        + UseCustomObsoletePrefix bool
        + CustomObsoletePrefix rune

        + RestoreLastCfg() 
        + ApplyOptions(opts ...PoOption) 

    }
    class PoParser << (S,Aquamarine) >> {
        - originalData []byte
        - data []byte
        - filename string
        - errors []error
        - warns []error

        + Config PoConfig

        - parseObsoleteEntries(tokens []lexer.Token) po.Entries

        + Error() error
        + Warnings() []error
        + Errors() []error
        + ParseWithOptions(opts ...PoOption) *po.File
        + Parse() *po.File

    }
    class entry << (S,Aquamarine) >> {
        + Tokens []lexer.Token
        + Context []string
        + ID []string
        + Str []string
        + MsgidPlural []string
        + Plurals []pluralEntries

    }
    class moHeader << (S,Aquamarine) >> {
        + MajorVersion u16
        + MinorVersion u16
        + MsgIDCount u32
        + MsgIDOffset u32
        + MsgStrOffset u32
        + HashSize u32
        + HashOffset u32

    }
    class parse.Endianness << (T, #FF7700) >>  {
    }
    class parse.MoOption << (T, #FF7700) >>  {
    }
    class parse.PoOption << (T, #FF7700) >>  {
    }
    class parse.i32 << (T, #FF7700) >>  {
    }
    class parse.i64 << (T, #FF7700) >>  {
    }
    class parse.u16 << (T, #FF7700) >>  {
    }
    class parse.u32 << (T, #FF7700) >>  {
    }
    class pluralEntries << (S,Aquamarine) >> {
        + ID int
        + Str []string

    }
    class poFile << (S,Aquamarine) >> {
        + Tokens []lexer.Token
        + Entries []entry

    }
    class "util.Endianness" as utilEndianness {
        'This class was created so that we can correctly have an alias pointing to this name. Since it contains dots that can break namespaces
    }
}


"__builtin__.int32" #.. "parse.i32"
"__builtin__.int64" #.. "parse.i64"
"__builtin__.uint16" #.. "parse.u16"
"__builtin__.uint32" #.. "parse.u32"
"parse.<font color=blue>func</font>(*MoConfig) " #.. "parse.MoOption"
"parse.<font color=blue>func</font>(*PoConfig) " #.. "parse.PoOption"
"parse.utilEndianness" #.. "parse.Endianness"
@enduml
