@startuml
namespace compiler {
    class MoCompiler << (S,Aquamarine) >> {
        + File *po.File
        + Config MoConfig

        - writeTo(writer io.Writer) error

        + SetFile(f *po.File) 
        + ToWriterWithOptions(w io.Writer, opts ...MoOption) error
        + ToBytesWithOptions(options ...MoOption) []byte
        + ToFileWithOptions(f string, options ...MoOption) error
        + ToWriter(w io.Writer) error
        + ToFile(f string) error
        + ToBytes() []byte

    }
    class MoConfig << (S,Aquamarine) >> {
        + Logger *log.Logger
        + Force bool
        + Verbose bool
        + IgnoreErrors bool

        + ApplyOptions(opts ...MoOption) 

    }
    class PoCompiler << (S,Aquamarine) >> {
        - nplurals uint
        - header po.Header

        + File *po.File
        + Config PoConfig

        - init() 
        - writeHeader(w io.Writer) 
        - fprintfln(w io.Writer, e po.Entry, format string, args ...any) 
        - writeComment(w io.Writer, e po.Entry) 
        - formatMultiline(str string) string
        - formatMsgstr(i string) string
        - formatMsgid(i string) string
        - writeEntry(w io.Writer, e po.Entry) 
        - formatPrefixAndSuffix(id string) string

        + SetFile(f *po.File) 
        + ToWriterWithOptions(w io.Writer, opts ...PoOption) error
        + ToStringWithOptions(opts ...PoOption) string
        + ToFileWithOptions(f string, opts ...PoOption) error
        + ToBytesWithOptions(opts ...PoOption) []byte
        + ToWriter(w io.Writer) error
        + ToFile(f string) error
        + ToString() string
        + ToBytes() []byte

    }
    class PoConfig << (S,Aquamarine) >> {
        + Logger *log.Logger
        + ForcePo bool
        + OmitHeader bool
        + PackageName string
        + CopyrightHolder string
        + ForeignUser bool
        + Title string
        + NoLocation bool
        + AddLocation PoLocationMode
        + MsgstrPrefix string
        + MsgstrSuffix string
        + IgnoreErrors bool
        + Verbose bool
        + CommentFuzzy bool
        + HeaderComments bool
        + HeaderFields bool
        + WordWrap bool

        + ApplyOptions(opts ...PoOption) 
        + Validate() error

    }
    class compiler.MoOption << (T, #FF7700) >>  {
    }
    class compiler.PoLocationMode << (T, #FF7700) >>  {
    }
    class compiler.PoOption << (T, #FF7700) >>  {
    }
    class compiler.u32 << (T, #FF7700) >>  {
    }
}


"__builtin__.string" #.. "compiler.PoLocationMode"
"__builtin__.uint32" #.. "compiler.u32"
"compiler.<font color=blue>func</font>(*MoConfig) " #.. "compiler.MoOption"
"compiler.<font color=blue>func</font>(*PoConfig) " #.. "compiler.PoOption"
@enduml
