name: Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3

      - name: Install gettext
        run: sudo apt install gettext
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "latest"
      - name: Test
        run: just test
      - name: Benchmark
        run: just benchmark
